<?php

return [
    'product_name' => ['label' => 'Product Name', 'print_key' => 'name', 'legacy' => true],
    'variation' => ['label' => 'Product Variation', 'print_key' => 'variations', 'legacy' => true],
    'selling_price' => ['label' => 'Selling Price', 'print_key' => 'price', 'legacy' => true],
    'business_name' => ['label' => 'Business Name', 'print_key' => 'business_name', 'legacy' => true],
    'packing_date' => ['label' => 'Packing Date', 'print_key' => 'packing_date', 'legacy' => true],
    'lot_number' => ['label' => 'Lot Number', 'print_key' => 'lot_number', 'legacy' => true],
    'expiry_date' => ['label' => 'Expiry Date', 'print_key' => 'exp_date', 'legacy' => true],
    'barcode' => ['label' => 'Barcode', 'print_key' => 'show_barcode', 'default' => true],
    'qr_code' => ['label' => 'QR Code', 'print_key' => 'show_qr_code'],
    'mrp' => ['label' => 'MRP', 'print_key' => 'show_mrp'],
    'batch_number' => ['label' => 'Batch Number', 'print_key' => 'show_batch_number'],
    'serial_number' => ['label' => 'Serial Number', 'print_key' => 'show_serial_number'],
    'model_number' => ['label' => 'Model Number', 'print_key' => 'show_model_number'],
    'sku' => ['label' => 'SKU', 'print_key' => 'show_sku'],
    'product_code' => ['label' => 'Product Code', 'print_key' => 'show_product_code'],
    'item_code' => ['label' => 'Item Code', 'print_key' => 'show_item_code'],
    'barcode_number' => ['label' => 'Barcode Number', 'print_key' => 'show_barcode_number'],
    'manufacturing_date' => ['label' => 'Manufacturing Date', 'print_key' => 'show_mfg_date'],
    'best_before' => ['label' => 'Best Before', 'print_key' => 'show_best_before'],
    'net_weight' => ['label' => 'Net Weight', 'print_key' => 'show_net_weight'],
    'gross_weight' => ['label' => 'Gross Weight', 'print_key' => 'show_gross_weight'],
    'unit' => ['label' => 'Unit', 'print_key' => 'show_unit'],
    'quantity' => ['label' => 'Quantity', 'print_key' => 'show_quantity'],
    'carton_number' => ['label' => 'Carton Number', 'print_key' => 'show_carton_number'],
    'po_number' => ['label' => 'PO Number', 'print_key' => 'show_po_number'],
    'invoice_number' => ['label' => 'Invoice Number', 'print_key' => 'show_invoice_number'],
    'branch_name' => ['label' => 'Branch Name', 'print_key' => 'show_branch_name'],
    'company_logo' => ['label' => 'Company Logo', 'print_key' => 'show_company_logo'],
    'country_of_origin' => ['label' => 'Country of Origin', 'print_key' => 'show_country_of_origin'],
    'custom_field_1' => ['label' => 'Custom Field 1', 'print_key' => 'show_custom_field_1'],
    'custom_field_2' => ['label' => 'Custom Field 2', 'print_key' => 'show_custom_field_2'],
    'custom_field_3' => ['label' => 'Custom Field 3', 'print_key' => 'show_custom_field_3'],
];
